server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/order_db
    username: root
    password: Gss@2194
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
  config:
      import: optional:configserver:http://localhost:9296
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-80881313.okta.com/oauth2/default
        client:
          registration:
            internal-client:
              provider: okta
              authorization-grant-type: client_credentials
              scope: internal
              client-id: 0oahmg2fotbm515WC5d7
              client-secret: un65WbL3mgSv1alivIVGsXic9sPaiQ8Wuv91vk53uL7T7Cskq1OJ5s1wVm0clj-0
          provider:
            okta:
              issuer-uri: https://dev-80881313.okta.com/oauth2/default


resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

management:
  tracing:
    probability: 1.0

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}